spring:
  datasource:
    url: jdbc:mysql://localhost:33060/springBootAngularDB
    username: homestead
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#    show-sql: true